sudo: required
dist: trusty

language: php

php:
  - 7.1

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  #- cd ./vendor/laravel/dusk/bin; chmod 775 *
  #- ./vendor/laravel/dusk/bin/chromedriver-linux &
  - phpenv config-rm xdebug.ini
  #- cd ../../../..
  - cp .env.travis .env
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - yarn
  - npm run production
  - phantomjs --webdriver=127.0.0.1:9515 &
  - php artisan serve &

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'

script:
  - vendor/bin/phpunit
  - php artisan dusk

services:
  - mysql

cache:
  yarn: true
  directories:
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="7.10"