sudo: required
dist: trusty

language: php

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - cp -rf .travis-tests phpunit.xml
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate
  - php artisan migrate
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - yarn

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS travis;'

script:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  yarn: true
  directories:
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="7.10"